apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: generic-pvc
  namespace: kubeflow
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs